version: '3.8'
services:
  talafoz:
    container_name: talafoz
    build: .
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - nginx

networks:
  nginx:
    external: true
    name: nginx
  
